BaSP-MR-56: Create activity list/delete table
BaSP-m2023/nai-megarocket-app pull request #1
Opened 2023-05-28 20:33 UTC by lorenzomauro59

I have created the list table with delete functionality with a modal to inform success of delete and styles for the page.

2023-05-28 20:47 UTC, AleMac17 requested changes

2023-05-28 20:47 UTC, AleMac17 commented on src/Components/Activities/Modals/modal.module.css
> +
We should not leave empty lines

2023-05-28 20:47 UTC, AleMac17 commented on src/Components/Activities/Table/index.js
> +
we should not leave empty lines

2023-05-28 22:04 UTC, AleMac17 approved these changes

2023-05-29 15:24 UTC, LucianoAlarcon approved these changes

2023-05-29 15:51 UTC, merged

2023-05-30 15:33 UTC, lorenzomauro59 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Activity] List/Delete table](https://trello.com/c/mv287KPM/56-activity-list-delete-table)

2023-06-06 16:34 UTC, nazarenapantanetti commented
Tested from master, bugs were found. Link to the report ticket https://trello.com/c/YcXRvhea/89-activity-bug-delete-errors