BaSP-MR-211 Trainer view setup - profile and shedule
BaSP-m2023/nai-megarocket-app pull request #112
Opened 2023-07-03 18:48 UTC by EmaBaldor

Trainer View Setup.
Create a Trainer folder in Components.
Create the Trainer private routes.
Create a Trainer view in /Views.
Modify the layout to display the Trainer view when the role is "TRAINER".
Create profile.
Create Schedule classes.

2023-07-03 19:04 UTC, EmaBaldor commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Trainer] Trainer View Setup](https://trello.com/c/Bj804FuB/211-trainer-trainer-view-setup)

2023-07-03 19:40 UTC, EmaBaldor commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Trainer] - Create profile](https://trello.com/c/a0rT0Q4e/218-trainer-create-profile)

2023-07-03 19:41 UTC, EmaBaldor commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Trainer] - Schedule](https://trello.com/c/H4R2E2k2/219-trainer-schedule)

2023-07-03 19:51 UTC, AleMac17 requested changes

2023-07-03 19:51 UTC, AleMac17 commented on src/Components/Trainer/Schedule/Modal/modalShedule.module.css
> +  font-size: 1.3rem;;
Ema, look this, double ;

2023-07-04 14:19 UTC, AleMac17 approved these changes

2023-07-04 17:00 UTC, fernandofernandezuy approved these changes
Great job Ema!

2023-07-05 00:43 UTC, merged

2023-07-07 22:15 UTC, araefe1992 commented
Great work Ema!! 😀😀😀