BaSP-HOTFIX-MR-104: Fix styles and made layout
BaSP-m2023/nai-megarocket-app pull request #39
Opened 2023-06-06 23:15 UTC by lorenzomauro59

We fix styles on the app and made an initial layout.

2023-06-06 23:33 UTC, Gonzarey96 approved these changes

2023-06-07 00:02 UTC, AleMac17 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[HOTFIX] - Fixed Styles](https://trello.com/c/B98UGv2L/104-hotfix-fixed-styles)

2023-06-07 00:30 UTC, EmaBaldor requested changes
It is necessary to add the styles to center the modal.

2023-06-07 00:35 UTC, lorenzomauro59 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[HOTFIX] - Fixed Styles](https://trello.com/c/B98UGv2L/104-hotfix-fixed-styles)

2023-06-07 01:22 UTC, EmaBaldor approved these changes

2023-06-07 01:34 UTC, merged