BaSP-MR-63: Subscription list delete table
BaSP-m2023/nai-megarocket-app pull request #5
Opened 2023-05-29 03:43 UTC by Federico-Peralta

-I created the list for the subscriptions 
-Added delete function
-Icons delete and edit

2023-05-29 16:06 UTC, danielninfi requested changes

2023-05-29 16:06 UTC, danielninfi commented on src/Components/Subscriptions/Modal/modal.module.css
> +  height: 8%;
this parameter should disturb the message box.
maybe you can fix it by removing it and modify margin or padding if necessary.

2023-05-29 17:42 UTC, danielninfi approved these changes
ok!

2023-05-30 01:22 UTC, LucianoAlarcon approved these changes

2023-05-30 01:22 UTC, LucianoAlarcon commented on src/Components/Subscriptions/Table/index.jsx
> +              <td>{item.classes.day[0] + ' - ' + item.classes.day[1]}</td>
Change this line to allow for the case that classes come empty and not break the app, please.
```suggestion
              <td>{item.classes ? item.classes.day[0] + ' - ' + item.classes.day[1] : 'No classes assigned'}</td>
```

2023-05-30 01:45 UTC, merged