BaSP-MR-121: Members redux put post
BaSP-m2023/nai-megarocket-app pull request #57
Opened 2023-06-12 21:47 UTC by EmaBaldor

Added redux logic to put and post member.
Completed thunks, actions, constans and reducers files.
The logic of the form was modified to use the data from the state.

2023-06-13 02:27 UTC, EmaBaldor commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Members] - Move post and put logic.](https://trello.com/c/piBP9uwG/121-members-move-post-and-put-logic)

2023-06-13 14:59 UTC, fernandofernandezuy commented on src/Components/Members/Form/index.jsx
> +      delete memberUpdate.__v;
You can do this when you set the member in the memberById() function, avoiding to declare a new constant

2023-06-13 14:59 UTC, fernandofernandezuy commented on src/Components/Members/Form/index.jsx
> +      setAlertMessage(`Member ${data.firstName} ${data.lastName} updated.`);
You can set the alert message using the response of the server, data.message

2023-06-13 14:59 UTC, fernandofernandezuy commented on src/Components/Members/Form/index.jsx
> +      setAlertMessage(`Member ${data.firstName} ${data.lastName} created.`);
Same here

2023-06-14 00:12 UTC, Federico-Peralta approved these changes
Tested!

2023-06-14 00:19 UTC, AleMac17 requested changes

2023-06-14 00:19 UTC, AleMac17 commented on src/Components/Members/index.jsx
> +  const [typeStyle, SetTypeStyle] = useState('');
We should use camelCase to nominate our variables. In this case -setTypeStyle-

2023-06-14 00:19 UTC, AleMac17 commented on src/Components/Members/index.jsx
> +      SetTypeStyle('success');
We should use camelCase to nominate our variables. In this case -setTypeStyle-

2023-06-14 00:19 UTC, AleMac17 commented on src/Components/Members/index.jsx
> +      SetTypeStyle('error');
We should use camelCase to nominate our variables. In this case -setTypeStyle-

2023-06-14 00:25 UTC, AleMac17 approved these changes

2023-06-14 00:28 UTC, merged

2023-06-16 23:40 UTC, araefe1992 commented
The functionality works correctly, Great Job!