BaSP-MR-153: React hook form implementation
BaSP-m2023/nai-megarocket-app pull request #68
Opened 2023-06-17 05:55 UTC by EmaBaldor

Update of the form, using 'react-hook-form' and implementation of the 'input' shared component. 
In addition, the corresponding validations were added.

2023-06-17 05:57 UTC, EmaBaldor commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Trainers] - React-hook-form implementation](https://trello.com/c/jtmRRsHd/153-trainers-react-hook-form-implementation)

2023-06-17 13:01 UTC, fernandofernandezuy requested changes

2023-06-17 13:01 UTC, fernandofernandezuy commented on src/Components/Trainers/Form/index.jsx
>    const trainers = useSelector((state) => state.trainers.data);
I think you could avoid getting all the trainers for this form, you could use a getById instead

2023-06-17 13:01 UTC, fernandofernandezuy commented on src/Components/Trainers/Form/index.jsx
> +          <Button type={'cancel'} clickAction={handleReset} text={'Reset'} />
Your reset button its not working properly, when i click it does the post or put method also.

2023-06-17 18:06 UTC, fernandofernandezuy approved these changes

2023-06-17 18:07 UTC, ale-schmidt reviewed
Please specify the name of the entity you are working on in the title of the PR

2023-06-17 18:13 UTC, ale-schmidt approved these changes
All working and looking fine :)

2023-06-17 18:14 UTC, merged

2023-06-23 03:12 UTC, nazarenapantanetti commented
Tested in master, changes requested! Follow the link to see the full report: https://trello.com/c/ntFGT8UP/182-trainer-bug-validations-fails