BaSP-MR-54: Class, List/Delete Table
BaSP-m2023/nai-megarocket-app pull request #7
Opened 2023-05-29 16:28 UTC by ale-schmidt

List table with delete functionality as well as a modal to confirm delete action created.

2023-05-29 16:41 UTC, danielninfi approved these changes

2023-05-29 20:37 UTC, lorenzomauro59 approved these changes
Everything looks well!

2023-05-30 01:50 UTC, LucianoAlarcon requested changes

2023-05-30 01:50 UTC, LucianoAlarcon commented on src/Components/Classes/Modal/index.jsx
> +  const CloseModal = () => {
Please renam this function to `closeMolda`

2023-05-30 01:50 UTC, LucianoAlarcon commented on src/Components/Classes/index.jsx
> +// import Form from './Form';
Delete this comment

2023-05-30 14:53 UTC, LucianoAlarcon approved these changes

2023-05-30 15:26 UTC, ale-schmidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Class] List/Delete table](https://trello.com/c/em2OKyQY/54-class-list-delete-table)

2023-05-30 15:34 UTC, merged