BaSP-MR-146: Admins react hook form implementation
BaSP-m2023/nai-megarocket-app pull request #72
Opened 2023-06-17 18:04 UTC by ale-schmidt

Update all current forms, along with the shared components (different types of inputs) used within them, following the documentation provided by React Hook Form. Additionally, the corresponding validations should be added to all forms.

As a final result, all forms in the frontend application should work with the React Hook Form library, maintaining a pleasant and consistent user experience, with all the respective validations for each input type and requirement, reusing components and functionalities.

- **Implement shared input ( HIGH PRIORITY )
- Update all current forms and shared components used in the forms (inputs). Take into account styles for errors
- Adding validations to forms (required fields, dates, names, number of characters). Using the JOI library)
- Add reset function button to clear fields**

2023-06-17 18:56 UTC, EmaBaldor approved these changes
God job!.
Note the styles so that it shows two columns of inputs.

2023-06-17 19:26 UTC, marcohzo requested changes

2023-06-17 19:26 UTC, marcohzo commented on src/validations/admins.jsx
> +    .max(20)
The maximum number of characters must match the server validations (max 16)

2023-06-17 19:54 UTC, marcohzo approved these changes
Good job!

2023-06-17 19:57 UTC, ale-schmidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Admins] - React-hook-form implementation](https://trello.com/c/kHQ5BD69/146-admins-react-hook-form-implementation)

2023-06-17 20:02 UTC, merged

2023-06-17 20:07 UTC, lorenzomauro59 commented on src/Components/Admins/Form/index.jsx
> +              inputType={'text'}
```suggestion
              inputType={'password'}
```

2023-06-17 20:10 UTC, lorenzomauro59 approved these changes
Only the detail that I commented, rest is working. Good job!!

2023-06-23 01:34 UTC, araefe1992 commented
I found a couple of validations in your bugs, I left you a ticket in Trello: https://trello.com/c/u4YWo8ft