BaSP-MR-167: [Admin] Reports
BaSP-m2023/nai-megarocket-app pull request #79
Opened 2023-06-19 18:17 UTC by marcohzo

- Create a path for reports inside the admin folder
- 3 navigation buttons created
- The activities screen show a graph with each activity loaded in the database with its respective quantity.
- The memberships screen display a graph with each memberships loaded into the database in each month.
- The members screen display a graph with each member loaded into the database in each month.

2023-06-20 16:15 UTC, AleMac17 requested changes

2023-06-20 16:15 UTC, AleMac17 commented on src/Components/Admin/Reports/Activities/index.jsx
> +  console.log(uniqueActivities);
We should not leave console logs in the code

2023-06-20 16:15 UTC, AleMac17 commented on src/Components/Admin/Reports/Activities/index.jsx
> +    // Verificar si no se encontraron actividades
We should not leave comments in the code

2023-06-20 18:33 UTC, AleMac17 approved these changes

2023-06-20 18:44 UTC, fernandofernandezuy commented
Looks great, can you put the activities report to the left? and give styles to the container, great job!

2023-06-20 20:42 UTC, fernandofernandezuy approved these changes
Looks good!, great job

2023-06-20 20:51 UTC, ale-schmidt approved these changes
Looks and works great!

2023-06-20 21:29 UTC, Gonzarey96 approved these changes

2023-06-20 21:30 UTC, merged

2023-06-21 13:12 UTC, fernandofernandezuy commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Admin: Reports] Create Admin > Reports screen](https://trello.com/c/CXD0MG4A/167-admin-reports-create-admin-reports-screen)

2023-06-22 19:07 UTC, nazarenapantanetti commented
Tested in master, changes requested! Follow the link to see the full report: https://trello.com/c/ZWzxF7pp/179-reports-bug-graph-is-not-clear